from .mscatalogo_service import ClienteCatalogoService
from .mscompras_service import ClienteComprasService
from .msinventario_service import ClienteInventarioService
from .mspagos_service import ClientePagosService
from .commerce_service import CommerceService